# https://goframe.org/docs/web/server-config-file-template
server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

# https://goframe.org/docs/core/glog-config
logger:
  level : "all"
  stdout: true

# https://goframe.org/docs/core/gdb-config-file
database:
  # 数据库类型选择: mysql 或 sqlite
  type: "mysql"  # 可以改为 "sqlite"
  sqlite:
    type: sqlite
    link: "sqlite::@file(./data/omniscient.sqlite3)"
    maxIdle: 10
    maxOpen: 100
    maxLifetime: 30
    debug: true
  mysql:
    link: "mysql:root:root@tcp(127.0.0.1:3306)/omniscient"
    maxIdle: 10
    maxOpen: 100
    maxLifetime: 30 # 连接最大生存时间（秒）
    debug: true     # 开启调试模式，方便排查问题
