
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "mysql:root:root@tcp(127.0.0.1:3306)/omniscient"
        descriptionTag: true

  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - omniscient/omniscient
  build:
    name:     "omniscient"
    arch:     "amd64,arm"
    system:   "linux"
    packSrc:  "resource,manifest"
    mod: ""
    cgo: 0
    version:  "v1.0.0.3"

